apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    berlioz_managed: "true"
    cluster: hello
    deployment: gext
    name: gext-hello-main-app
    sector: main
    service: app
  name: gext-hello-main-app
  namespace: hello
  resourceVersion: "783335"
  selfLink: /apis/extensions/v1beta1/namespaces/hello/deployments/gext-hello-main-app
  uid: cd9b0296-9c3f-11e9-93d8-42010a8a00a5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: gext-hello-main-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        berlioz_managed: "true"
        cluster: hello
        deployment: gext
        name: gext-hello-main-app
        sector: main
        service: app
    spec:
      containers:
      - env:
        - name: BERLIOZ_TASK_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: BERLIOZ_IDENTITY
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: BERLIOZ_ADDRESS
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: BERLIOZ_INSTANCE_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: BERLIOZ_HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: BERLIOZ_AGENT_PATH
          value: ws://${BERLIOZ_HOST_IP}:55555/${BERLIOZ_TASK_ID}
        - name: BERLIOZ_LISTEN_ADDRESS
          value: 0.0.0.0
        - name: BERLIOZ_INFRA
          value: k8s
        - name: BERLIOZ_REGION
          value: us-west1
        - name: BERLIOZ_CLUSTER
          value: hello
        - name: BERLIOZ_SECTOR
          value: main
        - name: BERLIOZ_SERVICE
          value: app
        - name: BERLIOZ_IDENTITY_PREFIX
          value: gext-hello-main-app-
        - name: BERLIOZ_LISTEN_PORT_DEFAULT
          value: "5000"
        - name: BERLIOZ_PROVIDED_PORT_DEFAULT
          value: "5000"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/service-key.json
        image: gcr.io/berlioz-external/hello-main-app@sha256:6ee143badaa282c2b6407b2eb9d1bf375388313fa41872c438d94281cdfc8bba
        imagePullPolicy: IfNotPresent
        name: gext-hello-main-app
        ports:
        - containerPort: 5000
          name: default
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/secrets/google
          name: google-cloud-key
      dnsPolicy: ClusterFirst
      priorityClassName: berlioz-normal-priority
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: google-cloud-key
        secret:
          defaultMode: 420
          secretName: gext-hello-main-app