---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    cluster: hello
    deployment: gprod
    name: gprod-hello-main-web
    sector: main
    service: web
  name: gprod-hello-main-web
  namespace: hello
  resourceVersion: "1458156"
  selfLink: /apis/extensions/v1beta1/namespaces/hello/deployments/gprod-hello-main-web
  uid: b2dfab4b-9ab3-11e9-b941-42010a8a0223
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: gprod-hello-main-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        berlioz_managed: "true"
        cluster: hello
        deployment: gprod
        name: gprod-hello-main-web
        sector: main
        service: web
    spec:
      containers:
      - image: gcr.io/berlioz-demo-fire/hello-main-web@sha256:c32a8dd4c3c03a98ba7a1ddb7b66966b7a1ea6e94af4b098df434f88bdfbe19c
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/service-key.json
        imagePullPolicy: IfNotPresent
        name: gprod-hello-main-web
        ports:
        - containerPort: 3000
          name: default
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /var/secrets/google
          name: google-cloud-key
      dnsPolicy: ClusterFirst
      priorityClassName: berlioz-normal-priority
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: google-cloud-key
        secret:
          defaultMode: 420
          secretName: gprod-hello-main-web
